MAIN_DIR = src
TEST_DIR = test

.PHONY: main test

all: main test

main:

test:

clean:

run-main:

run-test:
	@echo "[{\"methodName\":\"genericTest\",\"pointNames\": [\"1\", \"2\"], \"status\": \"PASSED\", \"message\": \"TestMessage\"}]" > test_output.txt

get-points:
	@echo "1\n2\n2\n"
